version: '3'
services:
        test:
                build:
                        context: .
                        dockerfile: test/Dockerfile
                command: /app/test/routine.sh
                #command: /bin/sh
                tty: true
                stdin_open: true
                volumes:
                        - "./:/app"
